sudo: false

language: node_js
dist: precise
osx_image: xcode8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

matrix:
  include:
    # linux
    - os: linux   # abi 47
      node_js: 5.1.1
      env: NODE_VERSION="5.1.1" CXX="g++-4.9"
    - os: linux   # abi 48
      node_js: 6
      env: NODE_VERSION="6" CXX="g++-4.9"
    - os: linux   # abi 49
      node_js: 6
      env: NODE_VERSION="6" ELECTRON="1.3.6" CXX="g++-4.9"
    - os: linux
      node_js: 12.4.0
      env: NODE_VERSION="12.4.0" ELECTRON="6.1.12" CXX="g++-4.9"
    - os: linux
      node_js: 12.8.1
      env: NODE_VERSION="12.8.1" ELECTRON="7.3.2" CXX="g++-4.9"
    # os x x86
    - os: osx
      node_js: 5.1.1
      env: NODE_VERSION="5.1.1" CXX="clang"
    - os: osx
      node_js: 6
      env: NODE_VERSION="6" CXX="clang"
    - os: osx
      node_js: 6
      env: NODE_VERSION="6" ELECTRON="1.3.6" CXX="clang"
    - os: osx
      node_js: 12.4.0
      env: NODE_VERSION="12.4.0" ELECTRON="6.1.12" CXX="clang"
    - os: osx
      node_js: 12.8.1
      env: NODE_VERSION="12.8.1" ELECTRON="7.3.2" CXX="clang"
      
before_install:
  - export PATH="./node_modules/.bin/:$PATH"

install:
  - if [[ -n "$ELECTRON" ]]; then
      export npm_config_target=$ELECTRON;
      export npm_config_disturl=https://atom.io/download/atom-shell;
      export npm_config_runtime=electron;
      export npm_config_build_from_source=true;
    fi
  - npm install

script:
  - if [[ -z "$ELECTRON" ]]; then
      npm test;
    fi
  - node-pre-gyp package testpackage

git:
  depth: 10

before_deploy:
  - export RELEASE_NODE_FILE=$(find build/stage -name '*.tar.gz')
  - echo "Deploying $RELEASE_NODE_FILE to GitHub"

deploy:
  provider: releases
  api_key:
    secure: O3QcxmbHw+ONU2KtfyLPulYY6Reas74xmSKBdxnbhyKnRGmuJo6X2+QE3F6TycA0IgY5PpV7PqM8V7rQ8+RgxJXRShq3EslZmf/ujUBn9nxX1mR61qjhclbQN6OLeWhUKEHp6Dz5xbqjO3NNDk4CdMPsa3DeBYjo8mDPFn96AQp4IoyM7GAUSC56t82xlyLqQ99pA235JH0YjL4V0s8YHLxMJDIzsDYWNz/BKk1Yck+MIeBlQtbwd4ZBSnnOJjkhkCzvdCtHN/rYRfM9I6T7BpFg0CgpccvGSZZ8zhuyAnvy9fI9MUiaA8e6gQYwbSEFFqokCohd7dsxbqURcbk80C/6w3DzmK51B5MQe8ozbFNHX0lNoKhzl9pQY76Gfa4atMD4dbQBsFu7aioYu/mR45cu4DPvDzE4E41lo/2f1B8dFgTvWoNqTdeZBZ1ths0rODHG7FO7nfzSwUPMYxJpNafcvs55FE7RiEKpeAEEAUubJSAfWvRGPxoAqBRxIjBzKwIt9L6zvnYHU/8P7Jp1zVHmRlguEa/CjkO1NmoCIbAHpDaRJv9rszV8o7I3CUYz67y8t7lgW0vlgH8iletN7LjE2bCEimdCgXRaeN4EyykxoGJf2BaHNuj1cIuHjpsqx9gDhuTL+fd45vm7DNSrFJPn106Uh6W42GxJ+/rTUbc=
  file: "$RELEASE_NODE_FILE"
  skip_cleanup: true
  on:
    repo: hansonw/fuzzy-native
    tags: true
